baseURL: https://yongtae.kim
languageCode: en-us
title: Yongtae Kim

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 3

# googleAnalytics: your-google-analytics-id
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/yongtae923
  # twitter: https://twitter.com/yongtae923
  # stackoverflow: your-stackoverflow-link
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Yongtae Kim
  # Author biography
  bio: Brain and Software Engineer
  # Site Description, used in HTML meat
  description: Yongtae Kim's Engineering Blog


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copyright, default: 'Â© Copyright 2021 â¤ï¸ {params.author}'
  copyright: 'Â© Copyright 2025 Yongtae Kim' 


  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: ğŸ‡ºğŸ‡¸ English
    params:
      author: Yongtae Kim
      bio: Brain and Software Engineer
      description: Yongtae Kim's Engineering Blog
    title: Yongtae Kim
    weight: 2

  ko:
    contentDir: content/ko
    disabled: false
    languageCode: ko-KR
    languageDirection: ltr
    languageName: ğŸ‡°ğŸ‡· í•œêµ­ì–´
    params:
      author: ê¹€ìš©íƒœ
      bio: ë‡Œì™€ ì†Œí”„íŠ¸ì›¨ì–´ ì—”ì§€ë‹ˆì–´
      description: ê¹€ìš©íƒœì˜ ì—”ì§€ë‹ˆì–´ë§ ë¸”ë¡œê·¸
    title: ê¹€ìš©íƒœ
    weight: 1